name: Release_Tags
on:
  push:
    tags:
      - "v*"  #on every tag created

env:
  service_name: expense-frontend

jobs:
  CI_Steps:
    uses: jyothsna-shrey/github-actions/.github/workflows/Release_Tags.yml@main


